//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimeManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.County = new HashSet<County>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int ProvinceID { get; set; }
    
        public virtual Province Province { get; set; }
        public virtual ICollection<County> County { get; set; }
    }
}
