//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimeManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int ID { get; set; }
        public int ProjectID { get; set; }
        public System.DateTime Date { get; set; }
        public int Money { get; set; }
        public string Type { get; set; }
        public int TaxPayed { get; set; }
        public string PayMethod { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
