//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimeManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyB
    {
        public PartyB()
        {
            this.Project = new HashSet<Project>();
            this.Invoice = new HashSet<Invoice>();
            this.Cost = new HashSet<Cost>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Project> Project { get; set; }
        public virtual ICollection<Invoice> Invoice { get; set; }
        public virtual ICollection<Cost> Cost { get; set; }
    }
}
