//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimeManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Invoice = new HashSet<Invoice>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int CountyID { get; set; }
        public string PartyAName { get; set; }
        public int PartyBID { get; set; }
        public string ResponsiblePerson { get; set; }
        public string ContactPhone { get; set; }
        public System.DateTime Date { get; set; }
        public int Money { get; set; }
    
        public virtual County County { get; set; }
        public virtual ICollection<Invoice> Invoice { get; set; }
        public virtual PartyB PartyB { get; set; }
    }
}
